apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::135874464415:user/github_ci
      username: github_ci
      groups:
        - system:masters
